#!/bin/sh /etc/rc.common

# Copyright (c) 2021 fantasticmao
USE_PROCD=1
START=99

NAME=node_exporter
NODE_EXPORTER_BIN="/usr/bin/node_exporter"

start_service() {
	nohup ${NODE_EXPORTER_BIN} > /dev/null &
	echo "${NAME} start success!"
}

stop_service() {
	kill $(pidof ${NAME})
	echo "${NAME} stopped."
}

reload_service() {
	stop_service
	start_service
}

service_running() {
	echo "pid of ${NAME}: $(pidof ${NAME})"
}

status_service() {
	service_running
}
